#!/bin/bash
#Commit and Push to Github

echo Starting Push
echo Would you like to choose one file? [y/n]

read UsrInput

if [ "$UsrInput" = "y" ]
then
	echo enter in file name
	read FileName
	cd find -name $FileName -printf '%h\n' | sort -u
	git add $FileName
else
	git add .
fi

echo Enter your commit message: 

read MessageVar

git commit -m "$MessageVar"

git push origin master
